{% set name = "scotch" %}
{% set build = 2 %}
{% set version = "6.0.9" %}
{% set sha256 = "622b4143cf01c480bb15708b3651b29c25e4aeb00c8c6447ff196aca2eca5c93" %}

{% set major = version.split('.')[0] %}
package:
  name: {{ name }}-pkgs
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://gforge.inria.fr/frs/download.php/latestfile/298/scotch_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patch1.diff
    - debian-dynamic.patch
    - use_predefined_headers.patch  # [osx and arm64]
    - use_predefined_headers_metis.patch  # [osx and arm64]

build:
  skip: true  # [win]
  number: {{ build }}

outputs:
  - name: scotch
    build:
      script: ${RECIPE_DIR}/build.sh
      run_exports:
        - {{ pin_subpackage('scotch', max_pin='x.x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        # preserve mpi variant for builds
        - mpi * {{ mpi }}
      host:
        - bison <3.8
        - flex
        - zlib
      run:
        - zlib

    test:
      requires:
        - {{ compiler('c') }}
      source_files:
        - src/check
        - src/libscotch/common.h
        - src/libscotch/module.h
        - src/libscotch/fibo.h
      files:
        - Makefile.inc
      commands:
        {% for lib in [
          'scotch',
          'scotcherr',
          'scotcherrexit',
          'scotchmetis',
          'esmumps',
        ]
        %}
        - test -f "${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}"
        - test -f "${PREFIX}/lib/lib{{ lib }}-{{ major }}${SHLIB_EXT}"
        {% endfor %}
        - test -f "${PREFIX}/include/scotch.h"
        - test -f "${PREFIX}/include/scotchf.h"
        - test -f "${PREFIX}/include/esmumps.h"
        - test -f "${PREFIX}/include/scotch/metis.h"
        - test ! -f "${PREFIX}/include/metis.h"
  - name: ptscotch
    build:
      script: ${RECIPE_DIR}/build.sh
      run_exports:
        - {{ pin_subpackage('ptscotch', max_pin='x.x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - flex
        - {{ mpi }}
        - scotch
        - zlib
      run:
        - {{ mpi }}
        - {{ pin_subpackage('scotch', max_pin='x.x.x') }}
        - zlib
    test:
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      source_files:
        - src/check
        - src/libscotch/common.h
        - src/libscotch/module.h
      files:
        - Makefile.inc
      commands:
        {% for lib in [
          'ptscotch',
          'ptscotcherr',
          'ptscotcherrexit',
          'ptscotchparmetis',
          'ptesmumps',
        ]
        %}
        - test -f "${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}"
        - test -f "${PREFIX}/lib/lib{{ lib }}-{{ major }}${SHLIB_EXT}"
        {% endfor %}
        - test -f "${PREFIX}/include/ptscotch.h"
        - test -f "${PREFIX}/include/ptscotchf.h"
        - test -f "${PREFIX}/include/esmumps.h"
        - test -f "${PREFIX}/include/scotch/parmetis.h"
        - test ! -f "${PREFIX}/include/parmetis.h"
    about:
      summary: 'PT-SCOTCH: (Parallel) Static Mapping, Graph, Mesh and Hypergraph Partitioning, and Parallel and Sequential Sparse Matrix Ordering Package'



about:
  home: https://www.labri.fr/perso/pelegrin/scotch/
  license: CECILL-C
  license_file: doc/CeCILL-C_V1-en.txt
  summary: 'SCOTCH: Static Mapping, Graph, Mesh and Hypergraph Partitioning, and Parallel and Sequential Sparse Matrix Ordering Package'
  description: |
    Software package and libraries for sequential and parallel
    graph partitioning, static mapping and clustering, sequential
    mesh and hypergraph partitioning, and sequential and parallel
    sparse matrix block ordering.
  doc_url: http://gforge.inria.fr/docman/?group_id=248&dirid=326
  dev_url: https://gitlab.inria.fr/scotch/scotch

extra:
  recipe-maintainers:
    - basnijholt
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - Tobias-Fischer
    - matthiasdiener
