{% set name = "scotch" %}
{% set version = "7.0.2" %}
{% set major = version.split('.')[0] %}
{% set minor = version.split('.')[1] %}

package:
  name: {{ name }}-pkgs
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://gitlab.inria.fr/scotch/scotch/-/archive/v{{ version }}/scotch-v{{ version }}.tar.gz
  sha256: 17db72097dea75522570fe26ece62d99d480a2ea49954181d87b3e1dc913e05b
  patches:
    # - patch1.diff
    - debian-dynamic.patch
    - dummysizes_cross_compile.patch

build:
  skip: true  # [win]
  number: 0

outputs:
  - name: scotch
    build:
      script: ${RECIPE_DIR}/build.sh
      run_exports:
        - {{ pin_subpackage('scotch', max_pin='x.x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        # preserve mpi variant for builds
        - mpi * {{ mpi }}
      host:
        - bison <3.8
        - flex
        - zlib
        - bzip2
        - xz
      run:
        - zlib

    test:
      requires:
        - {{ compiler('c') }}
      source_files:
        - src/check
        - src/libscotch/common.h
        - src/libscotch/module.h
        - src/libscotch/fibo.h
      files:
        - Makefile.inc
      commands:
        {% for lib in [
          'scotch',
          'scotcherr',
          'scotcherrexit',
          'scotchmetis',
          'esmumps',
        ]
        %}
        - test -f "${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}"
        - test -f "${PREFIX}/lib/lib{{ lib }}-{{ major }}.{{ minor }}${SHLIB_EXT}"
        {% endfor %}
        - test -f "${PREFIX}/include/scotch.h"
        - test -f "${PREFIX}/include/scotchf.h"
        - test -f "${PREFIX}/include/esmumps.h"
        - test -f "${PREFIX}/include/scotch/metis.h"
        - test ! -f "${PREFIX}/include/metis.h"
  - name: ptscotch
    build:
      script: ${RECIPE_DIR}/build.sh
      run_exports:
        - {{ pin_subpackage('ptscotch', max_pin='x.x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - flex
        - {{ mpi }}
        - scotch
        - zlib
      run:
        - {{ mpi }}
        - {{ pin_subpackage('scotch', max_pin='x.x.x') }}
        - zlib
    test:
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      source_files:
        - src/check
        - src/libscotch/common.h
        - src/libscotch/module.h
      files:
        - Makefile.inc
      commands:
        {% for lib in [
          'ptscotch',
          'ptscotcherr',
          'ptscotcherrexit',
          'ptscotchparmetis',
          'ptesmumps',
        ]
        %}
        - test -f "${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}"
        - test -f "${PREFIX}/lib/lib{{ lib }}-{{ major }}.{{ minor }}${SHLIB_EXT}"
        {% endfor %}
        - test -f "${PREFIX}/include/ptscotch.h"
        - test -f "${PREFIX}/include/ptscotchf.h"
        - test -f "${PREFIX}/include/esmumps.h"
        - test -f "${PREFIX}/include/scotch/parmetis.h"
        - test ! -f "${PREFIX}/include/parmetis.h"
    about:
      summary: 'PT-SCOTCH: (Parallel) Static Mapping, Graph, Mesh and Hypergraph Partitioning, and Parallel and Sequential Sparse Matrix Ordering Package'



about:
  home: https://www.labri.fr/perso/pelegrin/scotch/
  license: CECILL-C
  license_file: doc/CeCILL-C_V1-en.txt
  summary: 'SCOTCH: Static Mapping, Graph, Mesh and Hypergraph Partitioning, and Parallel and Sequential Sparse Matrix Ordering Package'
  description: |
    Software package and libraries for sequential and parallel
    graph partitioning, static mapping and clustering, sequential
    mesh and hypergraph partitioning, and sequential and parallel
    sparse matrix block ordering.
  doc_url: http://gforge.inria.fr/docman/?group_id=248&dirid=326
  dev_url: https://gitlab.inria.fr/scotch/scotch

extra:
  recipe-maintainers:
    - basnijholt
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - Tobias-Fischer
    - matthiasdiener
