{% set name = "scotch" %}
{% set version = "7.0.3" %}
{% set major = version.split('.')[0] %}
{% set minor = version.split('.')[1] %}

package:
  name: {{ name }}-pkgs
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://gitlab.inria.fr/scotch/scotch/-/archive/v{{ version }}/scotch-v{{ version }}.tar.gz
  sha256: 5b5351f0ffd6fcae9ae7eafeccaa5a25602845b9ffd1afb104db932dd4d4f3c5
  patches:
    - 0001-Remove-unconditional-testing.patch
    - 0002-add-COMPONENT-labels-for-easier-split-installation.patch
    - 0003-put-metis-headers-in-include-scotch.patch
    - 0004-fix-language-requirement.patch
    - 0005-use-external-dummysizes.patch
    - 0006-fix-ptesmumps.h.patch
    - 0007-fix-empty-union.patch
    - 0008-win-fix-ssize_t.patch
    - 0009-win-fix-context.c.patch  # [win]
    - 0010-win-fix-flex.patch
    - 0011-win-do-not-link-m.patch
    - 0012-win-fix-threads.patch
    - 0013-win-fix-graph-match-scan.patch
    - 0014-win-disable-fortran-test.patch
    - 0015-win-fix-unistd-time-include.patch
    - 0016-win-fix-exports.patch

build:
  number: 1

outputs:
  - name: libscotch
    build:
      script: ${RECIPE_DIR}/build-scotch.sh   # [unix]
      script: "%RECIPE_DIR%\\bld-scotch.bat"  # [win]
      run_exports:
        - {{ pin_subpackage('scotch', max_pin='x.x.x') }}
      ignore_run_exports:
        - {{ mpi }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
        - cmake
        - make
        - ninja         # [win]
        - {{ mpi }}     # [build_platform != target_platform]
        - bison <3.8    # [unix]
        - flex          # [unix]
        - winflexbison  # [win]
      host:
        - zlib
        - bzip2
        - xz
        - {{ mpi }}
        - pthreads-win32  # [win]
      run:
        - zlib
        - pthreads-win32  # [win]

    test:
      requires:
        - {{ compiler('c') }}
      commands:
        {% for lib in [
          'scotch',
          'scotcherr',
          'scotcherrexit',
          'esmumps',
        ]
        %}
        - test -f "${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}"                       # [unix]
        - if exist %PREFIX%\\Library\\lib\\{{ lib }}.lib (exit 0) else (exit 1)  # [win]
        {% endfor %}
        - test -f "${PREFIX}/include/scotch.h"                                   # [unix]
        - if exist %PREFIX%\\Library\\include\\scotch.h (exit 0) else (exit 1)   # [win]
        - test -f "${PREFIX}/include/scotchf.h"                                  # [unix]
        - if exist %PREFIX%\\Library\\include\\scotchf.h (exit 0) else (exit 1)  # [win]
        - test -f "${PREFIX}/include/esmumps.h"                                  # [unix]
        - if exist %PREFIX%\\Library\\include\\esmumps.h (exit 0) else (exit 1)  # [win]
        - test ! -f "${PREFIX}/include/metis.h"                                  # [unix]
        - test -f "${PREFIX}/include/scotch/metis.h"                             # [unix]
        - if exist %PREFIX%\\Library\\include\\scotch\\metis.h (exit 0) else (exit 1)  # [win]
        - test ! -f "${PREFIX}/bin/gord"                                         # [unix]

  - name: libptscotch
    build:
      script:
        - cmake --install ./build --component=libptscotch
      run_exports:
        - {{ pin_subpackage('ptscotch', max_pin='x.x.x') }}
    requirements:
      build:
        - cmake
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - {{ mpi }}
      run:
        - {{ pin_subpackage("scotch", exact=True) }}
    test:
      requires:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      commands:
        {% for lib in [
          'ptscotch',
          'ptscotcherr',
          'ptscotcherrexit',
          'ptesmumps'
        ]
        %}
        - test -f "${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}"                         # [unix]
        - if exist %PREFIX%\\Library\\lib\\{{ lib }}.lib (exit 0) else (exit 1)    # [win]
        {% endfor %}
        - test -f "${PREFIX}/include/ptscotch.h"                                   # [unix]
        - if exist %PREFIX%\\Library\\include\\ptscotch.h (exit 0) else (exit 1)   # [win]
        - test -f "${PREFIX}/include/ptscotchf.h"                                  # [unix]
        - if exist %PREFIX%\\Library\\include\\ptscotchf.h (exit 0) else (exit 1)  # [win]
        - test -f "${PREFIX}/include/ptesmumps.h"                                  # [unix]
        - if exist %PREFIX%\\Library\\include\\ptesmumps.h (exit 0) else (exit 1)  # [win]
        - test -f "${PREFIX}/include/scotch/parmetis.h"                            # [unix]
        - if exist %PREFIX%\\Library\\include\\patmetis.h (exit 0) else (exit 1)   # [win]
        - test ! -f "${PREFIX}/include/parmetis.h"                                 # [unix]
        - test ! -f "${PREFIX}/bin/dgord"                                          # [unix]
    about:
      summary: 'PT-SCOTCH: (Parallel) Static Mapping, Graph, Mesh and Hypergraph Partitioning, and Parallel and Sequential Sparse Matrix Ordering Package'

  - name: scotch
    build:
      script: cmake --install ./build --component=scotch
      run_exports:
        - {{ pin_subpackage('scotch', max_pin='x.x.x') }}
      ignore_run_exports:
        - {{ mpi }}
    requirements:
      build:
        - cmake
      host:
        # This is needed to get the correct package hash
        - {{ mpi }}
      run:
        - {{ pin_subpackage('libscotch', exact=True) }}
    test:
      commands:
        - test -f "${PREFIX}/bin/gord"                          # [unix]
        - if exist %PREFIX%\\bin\\gord (exit 0) else (exit 1)   # [win]
        - test ! -f "${PREFIX}/bin/dgord"                       # [unix]

  - name: ptscotch
    build:
      script: cmake --install ./build --component=ptscotch
      run_exports:
        - {{ pin_subpackage('ptscotch', max_pin='x.x.x') }}
    requirements:
      build:
        - cmake
      host:
        # This is needed to get the correct package hash
        - {{ mpi }}
      run:
        - {{ pin_subpackage('libptscotch', exact=True) }}
        - {{ pin_subpackage('scotch', exact=True) }}
    test:
      commands:
        - test -f "${PREFIX}/bin/gord"                          # [unix]
        - if exist %PREFIX%\\bin\\gord (exit 0) else (exit 1)   # [win]
        - test -f "${PREFIX}/bin/dgord"                         # [unix]
        - if exist %PREFIX%\\bin\\dgord (exit 0) else (exit 1)  # [win]
    about:
      summary: 'PT-SCOTCH: (Parallel) Static Mapping, Graph, Mesh and Hypergraph Partitioning, and Parallel and Sequential Sparse Matrix Ordering Package'

about:
  home: https://www.labri.fr/perso/pelegrin/scotch/
  license: CECILL-C
  license_file: doc/CeCILL-C_V1-en.txt
  summary: 'SCOTCH: Static Mapping, Graph, Mesh and Hypergraph Partitioning, and Parallel and Sequential Sparse Matrix Ordering Package'
  description: |
    Software package and libraries for sequential and parallel
    graph partitioning, static mapping and clustering, sequential
    mesh and hypergraph partitioning, and sequential and parallel
    sparse matrix block ordering.
  doc_url: http://gforge.inria.fr/docman/?group_id=248&dirid=326
  dev_url: https://gitlab.inria.fr/scotch/scotch

extra:
  recipe-maintainers:
    - basnijholt
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - Tobias-Fischer
    - matthiasdiener
